Exp:
  out_dir: "output/AE/cxad/"
  gpu: 1

Model:
  network: "AE"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  ls: 16  # the output size of encoder
  mem_dim: Null
  shrink_thres: Null

Data:
  dataset: "cxad"  # rsna, vin
  img_size: 64
  extra_data: 2000  # unlabeled data for module A
  ar: 0.6  # anomaly rate in unlabeled data for module A

Solver:
  bs: 64
  lr: 5.0e-4
  weight_decay: 0
  num_epoch: 250
