Exp:
  out_dir: "output/MemAE/rsna/"
  gpu: 0

Model:
  network: "MemAE"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  ls: 16  # the output size of encoder
  mem_dim: 25
  shrink_thres: 0.0
  entropy_loss_weight: 0.0002

Data:
  dataset: "rsna"  # rsna, vin
  img_size: 64
  extra_data: 4000  # unlabeled data for module A
  ar: 0.6  # anomaly rate in unlabeled data for module A

Solver:
  bs: 64
  lr: 5.0e-4
  weight_decay: 0
  num_epoch: 250
